### ISSUE TITLE
Stopped working at all

### ISSUE THREAD

**Issue by avxkim** [yavorsky/SublimeBump#8]
Here's the error i'm getting in console:

```
  File "/Users/***/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/request.py", line 22, in fetch_package_version
    callback(response['version'])
KeyError: 'version'
```

Seems like they changed something

**Comment by ghost** [comment]
I also have an error : 
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/damienbernard/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/bump.py", line 43, in on_selection_modified_async
    self.display_version_for_line(view, tooltip=True)
  File "/Users/damienbernard/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/bump.py", line 48, in display_version_for_line
    persist.worker.log_version_for_view(view)
  File "/Users/damienbernard/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/persist.py", line 102, in log_version_for_view
    self.from_cache_or_fetch(package, distribution_mode, vid, callback)
  File "/Users/damienbernard/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/persist.py", line 36, in from_cache_or_fetch
    try: request.fetch_package_version(package, distribution_mode, callback)
  File "/Users/damienbernard/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/request.py", line 22, in fetch_package_version
    callback(response['version'])
KeyError: 'version'
```

**Comment by alexbet** [comment]
Same here, here is the error

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/User/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/commands.py", line 172, in run
  File "/Users/User/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/persist.py", line 61, in run_bump_with_mode
  File "/Users/User/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/persist.py", line 36, in from_cache_or_fetch
  File "/Users/User/Library/Application Support/Sublime Text 3/Installed Packages/Bump.sublime-package/request.py", line 22, in fetch_package_version
KeyError: 'version'`

**Comment by navaru** [comment]
The fix is on this fork: https://github.com/olegafx/Bump/tree/fix_fetching

**Comment by alexbet** [comment]
Thanks @ugin ! Do I need to manually install this fork, or it can be downloaded as a package in Sublime?

**Comment by navaru** [comment]
@alexbet  if you're on a Mac manually clone it:

```
git clone -b fix_fetching --single-branch https://github.com/olegafx/Bump.git $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/Bump
```

**Comment by alexbet** [comment]
@ugin I am getting this error when I try it:

`fatal: Remote branch fix_fetching not found in upstream origin`

**Comment by navaru** [comment]
Sorry, fixed the URL in the above comment.

**Comment by avxkim** [comment]
@ugin are you willing to maintain this package in the future? Seems like the original author has no free time.
